// movies
export const FETCHING_PHONE_LIST = 'FETCHING_PHONES'
export const PHONE_LIST_FETCHED = 'PHONES_LIST_FETCHED'
export const FILTERING_LIST = 'FILTERING_LIST'
export const LIST_FILTERED = 'FILTER_SEARCH'
